//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Struds.Net.TidePredictor.Domain.Localisation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Struds.Net.TidePredictor.Domain.Localisation.Resource_de", typeof(Resource_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AddDryingHeightCaption {
            get {
                return ResourceManager.GetString("AddDryingHeightCaption", resourceCulture);
            }
        }
        
        public static string AddFallToNextLowWaterCaption {
            get {
                return ResourceManager.GetString("AddFallToNextLowWaterCaption", resourceCulture);
            }
        }
        
        public static string AllTimesLocalCaption {
            get {
                return ResourceManager.GetString("AllTimesLocalCaption", resourceCulture);
            }
        }
        
        public static string AllTimesUtcCaption {
            get {
                return ResourceManager.GetString("AllTimesUtcCaption", resourceCulture);
            }
        }
        
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        public static byte[] arrow_collapse_down_24 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_down_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] arrow_collapse_down_36 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_down_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] arrow_collapse_down_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_down_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] arrow_collapse_up_24 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_up_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] arrow_collapse_up_36 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_up_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] arrow_collapse_up_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_up_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static string BusyContentCaption {
            get {
                return ResourceManager.GetString("BusyContentCaption", resourceCulture);
            }
        }
        
        public static string CalculationsCaption {
            get {
                return ResourceManager.GetString("CalculationsCaption", resourceCulture);
            }
        }
        
        public static string ChartYAxisTitle {
            get {
                return ResourceManager.GetString("ChartYAxisTitle", resourceCulture);
            }
        }
        
        public static string ChooseEndDateCaption {
            get {
                return ResourceManager.GetString("ChooseEndDateCaption", resourceCulture);
            }
        }
        
        public static string ChooseStartDateCaption {
            get {
                return ResourceManager.GetString("ChooseStartDateCaption", resourceCulture);
            }
        }
        
        public static string ClearChartedObjectHeaderCaption {
            get {
                return ResourceManager.GetString("ClearChartedObjectHeaderCaption", resourceCulture);
            }
        }
        
        public static string ColumnHeaderIsFavorite {
            get {
                return ResourceManager.GetString("ColumnHeaderIsFavorite", resourceCulture);
            }
        }
        
        public static string ColumnHeaderTideHeight {
            get {
                return ResourceManager.GetString("ColumnHeaderTideHeight", resourceCulture);
            }
        }
        
        public static string ColumnHeaderTideRange {
            get {
                return ResourceManager.GetString("ColumnHeaderTideRange", resourceCulture);
            }
        }
        
        public static string ColumnHeaderTideState {
            get {
                return ResourceManager.GetString("ColumnHeaderTideState", resourceCulture);
            }
        }
        
        public static string ColumnHeaderTideStation {
            get {
                return ResourceManager.GetString("ColumnHeaderTideStation", resourceCulture);
            }
        }
        
        public static string ColumnHeaderTideTime {
            get {
                return ResourceManager.GetString("ColumnHeaderTideTime", resourceCulture);
            }
        }
        
        public static string FavoriteTideStationsTitle {
            get {
                return ResourceManager.GetString("FavoriteTideStationsTitle", resourceCulture);
            }
        }
        
        public static string FromCaption {
            get {
                return ResourceManager.GetString("FromCaption", resourceCulture);
            }
        }
        
        public static string GetTideHeightsCaption {
            get {
                return ResourceManager.GetString("GetTideHeightsCaption", resourceCulture);
            }
        }
        
        public static string HeightCaption {
            get {
                return ResourceManager.GetString("HeightCaption", resourceCulture);
            }
        }
        
        public static string HeightOfTideRequiredCaption {
            get {
                return ResourceManager.GetString("HeightOfTideRequiredCaption", resourceCulture);
            }
        }
        
        public static byte[] help_box_24 {
            get {
                object obj = ResourceManager.GetObject("help_box_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] help_box_36 {
            get {
                object obj = ResourceManager.GetObject("help_box_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] help_box_48 {
            get {
                object obj = ResourceManager.GetObject("help_box_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static string HighWater {
            get {
                return ResourceManager.GetString("HighWater", resourceCulture);
            }
        }
        
        public static string IntervalCaption {
            get {
                return ResourceManager.GetString("IntervalCaption", resourceCulture);
            }
        }
        
        public static string LandingPageCaption {
            get {
                return ResourceManager.GetString("LandingPageCaption", resourceCulture);
            }
        }
        
        public static string LocalCaption {
            get {
                return ResourceManager.GetString("LocalCaption", resourceCulture);
            }
        }
        
        public static string LowWater {
            get {
                return ResourceManager.GetString("LowWater", resourceCulture);
            }
        }
        
        public static string ManageFavoriteTideStationsTitle {
            get {
                return ResourceManager.GetString("ManageFavoriteTideStationsTitle", resourceCulture);
            }
        }
        
        public static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        public static byte[] minus_24 {
            get {
                object obj = ResourceManager.GetObject("minus_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] minus_36 {
            get {
                object obj = ResourceManager.GetObject("minus_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] minus_48 {
            get {
                object obj = ResourceManager.GetObject("minus_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static string MinutesCaptions {
            get {
                return ResourceManager.GetString("MinutesCaptions", resourceCulture);
            }
        }
        
        public static string MobileApplicationTitle {
            get {
                return ResourceManager.GetString("MobileApplicationTitle", resourceCulture);
            }
        }
        
        public static string NavigationButtonCaptionBack {
            get {
                return ResourceManager.GetString("NavigationButtonCaptionBack", resourceCulture);
            }
        }
        
        public static string NextLowWaterHeightCaption {
            get {
                return ResourceManager.GetString("NextLowWaterHeightCaption", resourceCulture);
            }
        }
        
        public static string NextLowWaterTimeCaption {
            get {
                return ResourceManager.GetString("NextLowWaterTimeCaption", resourceCulture);
            }
        }
        
        public static string PickFromListCaption {
            get {
                return ResourceManager.GetString("PickFromListCaption", resourceCulture);
            }
        }
        
        public static string PickFromMapCaption {
            get {
                return ResourceManager.GetString("PickFromMapCaption", resourceCulture);
            }
        }
        
        public static byte[] plus_24 {
            get {
                object obj = ResourceManager.GetObject("plus_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] plus_36 {
            get {
                object obj = ResourceManager.GetObject("plus_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] plus_48 {
            get {
                object obj = ResourceManager.GetObject("plus_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static string RefreshTimeHeightTooltip {
            get {
                return ResourceManager.GetString("RefreshTimeHeightTooltip", resourceCulture);
            }
        }
        
        public static string SafeAnchorDepthCaption {
            get {
                return ResourceManager.GetString("SafeAnchorDepthCaption", resourceCulture);
            }
        }
        
        public static string SafeAnchoringDepthHeaderCaption {
            get {
                return ResourceManager.GetString("SafeAnchoringDepthHeaderCaption", resourceCulture);
            }
        }
        
        public static string SelectedTideHeightCaption {
            get {
                return ResourceManager.GetString("SelectedTideHeightCaption", resourceCulture);
            }
        }
        
        public static string SelectedTideStationCaption {
            get {
                return ResourceManager.GetString("SelectedTideStationCaption", resourceCulture);
            }
        }
        
        public static string ShowOnTideCurveCaption {
            get {
                return ResourceManager.GetString("ShowOnTideCurveCaption", resourceCulture);
            }
        }
        
        public static string ShowTideCurveCaption {
            get {
                return ResourceManager.GetString("ShowTideCurveCaption", resourceCulture);
            }
        }
        
        public static string ShowTimeInUtcCaption {
            get {
                return ResourceManager.GetString("ShowTimeInUtcCaption", resourceCulture);
            }
        }
        
        public static byte[] sine_wave_24 {
            get {
                object obj = ResourceManager.GetObject("sine_wave_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] sine_wave_36 {
            get {
                object obj = ResourceManager.GetObject("sine_wave_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] sine_wave_48 {
            get {
                object obj = ResourceManager.GetObject("sine_wave_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static string SnackbarMessageLoadingComplete {
            get {
                return ResourceManager.GetString("SnackbarMessageLoadingComplete", resourceCulture);
            }
        }
        
        public static string SnackbarMessageLoadingTideStations {
            get {
                return ResourceManager.GetString("SnackbarMessageLoadingTideStations", resourceCulture);
            }
        }
        
        public static string SubtractChartedDepthCaption {
            get {
                return ResourceManager.GetString("SubtractChartedDepthCaption", resourceCulture);
            }
        }
        
        public static string TideHeight {
            get {
                return ResourceManager.GetString("TideHeight", resourceCulture);
            }
        }
        
        public static string TideHeightsIntervalCaption {
            get {
                return ResourceManager.GetString("TideHeightsIntervalCaption", resourceCulture);
            }
        }
        
        public static string TideHeightsIntervalTooltip {
            get {
                return ResourceManager.GetString("TideHeightsIntervalTooltip", resourceCulture);
            }
        }
        
        public static string TideHeightsTitle {
            get {
                return ResourceManager.GetString("TideHeightsTitle", resourceCulture);
            }
        }
        
        public static string TideStationsCaption {
            get {
                return ResourceManager.GetString("TideStationsCaption", resourceCulture);
            }
        }
        
        public static string TidesTitle {
            get {
                return ResourceManager.GetString("TidesTitle", resourceCulture);
            }
        }
        
        public static string TideTimeCaption {
            get {
                return ResourceManager.GetString("TideTimeCaption", resourceCulture);
            }
        }
        
        public static string TimeCaption {
            get {
                return ResourceManager.GetString("TimeCaption", resourceCulture);
            }
        }
        
        public static string ToCaption {
            get {
                return ResourceManager.GetString("ToCaption", resourceCulture);
            }
        }
        
        public static string TodaysTidesCaption {
            get {
                return ResourceManager.GetString("TodaysTidesCaption", resourceCulture);
            }
        }
        
        public static string TooltipFindMyLocation {
            get {
                return ResourceManager.GetString("TooltipFindMyLocation", resourceCulture);
            }
        }
        
        public static string TooltipVesselDraught {
            get {
                return ResourceManager.GetString("TooltipVesselDraught", resourceCulture);
            }
        }
        
        public static string TooltipVesselSafetyFactor {
            get {
                return ResourceManager.GetString("TooltipVesselSafetyFactor", resourceCulture);
            }
        }
        
        public static string TotalDraughtNeededCaption {
            get {
                return ResourceManager.GetString("TotalDraughtNeededCaption", resourceCulture);
            }
        }
        
        public static string UtcCaption {
            get {
                return ResourceManager.GetString("UtcCaption", resourceCulture);
            }
        }
        
        public static string VesselDetailsCaption {
            get {
                return ResourceManager.GetString("VesselDetailsCaption", resourceCulture);
            }
        }
        
        public static string VesselDraughtCaption {
            get {
                return ResourceManager.GetString("VesselDraughtCaption", resourceCulture);
            }
        }
        
        public static string VesselSafetyFactorCaption {
            get {
                return ResourceManager.GetString("VesselSafetyFactorCaption", resourceCulture);
            }
        }
        
        public static string ViewTideStationsMapCaption {
            get {
                return ResourceManager.GetString("ViewTideStationsMapCaption", resourceCulture);
            }
        }
        
        public static byte[] waves_24 {
            get {
                object obj = ResourceManager.GetObject("waves_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] waves_36 {
            get {
                object obj = ResourceManager.GetObject("waves_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] waves_48 {
            get {
                object obj = ResourceManager.GetObject("waves_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static string LoadingTideHeightsMessage {
            get {
                return ResourceManager.GetString("LoadingTideHeightsMessage", resourceCulture);
            }
        }
        
        public static string EmptyTideHeightsData {
            get {
                return ResourceManager.GetString("EmptyTideHeightsData", resourceCulture);
            }
        }
        
        public static string SaveFileCaption {
            get {
                return ResourceManager.GetString("SaveFileCaption", resourceCulture);
            }
        }
        
        public static string SaveFileFilter {
            get {
                return ResourceManager.GetString("SaveFileFilter", resourceCulture);
            }
        }
        
        public static string CsvExportCompleteMessage {
            get {
                return ResourceManager.GetString("CsvExportCompleteMessage", resourceCulture);
            }
        }
        
        public static string ExportToCsvCaption {
            get {
                return ResourceManager.GetString("ExportToCsvCaption", resourceCulture);
            }
        }
    }
}
