//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Struds.Net.TidePredictor.Domain.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Struds.Net.TidePredictor.Domain.Localisation.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Drying Height:.
        /// </summary>
        public static string AddDryingHeightCaption {
            get {
                return ResourceManager.GetString("AddDryingHeightCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tidal Fall Between Now and Next LW:.
        /// </summary>
        public static string AddFallToNextLowWaterCaption {
            get {
                return ResourceManager.GetString("AddFallToNextLowWaterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Times shown in Local.
        /// </summary>
        public static string AllTimesLocalCaption {
            get {
                return ResourceManager.GetString("AllTimesLocalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Times shown in UTC.
        /// </summary>
        public static string AllTimesUtcCaption {
            get {
                return ResourceManager.GetString("AllTimesUtcCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide Predictor.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] arrow_collapse_down_24 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_down_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] arrow_collapse_down_36 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_down_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] arrow_collapse_down_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_down_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] arrow_collapse_up_24 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_up_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] arrow_collapse_up_36 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_up_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] arrow_collapse_up_48 {
            get {
                object obj = ResourceManager.GetObject("arrow_collapse_up_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data.
        /// </summary>
        public static string BusyContentCaption {
            get {
                return ResourceManager.GetString("BusyContentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations.
        /// </summary>
        public static string CalculationsCaption {
            get {
                return ResourceManager.GetString("CalculationsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide Height (Metres).
        /// </summary>
        public static string ChartYAxisTitle {
            get {
                return ResourceManager.GetString("ChartYAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose End Date.
        /// </summary>
        public static string ChooseEndDateCaption {
            get {
                return ResourceManager.GetString("ChooseEndDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Start Date.
        /// </summary>
        public static string ChooseStartDateCaption {
            get {
                return ResourceManager.GetString("ChooseStartDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Charted Object.
        /// </summary>
        public static string ClearChartedObjectHeaderCaption {
            get {
                return ResourceManager.GetString("ClearChartedObjectHeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string ColumnHeaderIsFavorite {
            get {
                return ResourceManager.GetString("ColumnHeaderIsFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ColumnHeaderTideHeight {
            get {
                return ResourceManager.GetString("ColumnHeaderTideHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string ColumnHeaderTideRange {
            get {
                return ResourceManager.GetString("ColumnHeaderTideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide State.
        /// </summary>
        public static string ColumnHeaderTideState {
            get {
                return ResourceManager.GetString("ColumnHeaderTideState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide Station.
        /// </summary>
        public static string ColumnHeaderTideStation {
            get {
                return ResourceManager.GetString("ColumnHeaderTideStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ColumnHeaderTideTime {
            get {
                return ResourceManager.GetString("ColumnHeaderTideTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Tide Data.
        /// </summary>
        public static string CompareTideData {
            get {
                return ResourceManager.GetString("CompareTideData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed CSV Export to {0}.
        /// </summary>
        public static string CsvExportCompleteMessage {
            get {
                return ResourceManager.GetString("CsvExportCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tide Height Data Found.
        /// </summary>
        public static string EmptyTideHeightsData {
            get {
                return ResourceManager.GetString("EmptyTideHeightsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string ExportToCsvCaption {
            get {
                return ResourceManager.GetString("ExportToCsvCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Tide Stations.
        /// </summary>
        public static string FavoriteTideStationsTitle {
            get {
                return ResourceManager.GetString("FavoriteTideStationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string FromCaption {
            get {
                return ResourceManager.GetString("FromCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Tide Heights.
        /// </summary>
        public static string GetTideHeightsCaption {
            get {
                return ResourceManager.GetString("GetTideHeightsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string HeightCaption {
            get {
                return ResourceManager.GetString("HeightCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height of Tide Required:.
        /// </summary>
        public static string HeightOfTideRequiredCaption {
            get {
                return ResourceManager.GetString("HeightOfTideRequiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] help_box_24 {
            get {
                object obj = ResourceManager.GetObject("help_box_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] help_box_36 {
            get {
                object obj = ResourceManager.GetObject("help_box_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] help_box_48 {
            get {
                object obj = ResourceManager.GetObject("help_box_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Water.
        /// </summary>
        public static string HighWater {
            get {
                return ResourceManager.GetString("HighWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval:.
        /// </summary>
        public static string IntervalCaption {
            get {
                return ResourceManager.GetString("IntervalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Tide Station.
        /// </summary>
        public static string LandingPageCaption {
            get {
                return ResourceManager.GetString("LandingPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Tide Heights Data....
        /// </summary>
        public static string LoadingTideHeightsMessage {
            get {
                return ResourceManager.GetString("LoadingTideHeightsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string LocalCaption {
            get {
                return ResourceManager.GetString("LocalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Water.
        /// </summary>
        public static string LowWater {
            get {
                return ResourceManager.GetString("LowWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favorite Tide Stations.
        /// </summary>
        public static string ManageFavoriteTideStationsTitle {
            get {
                return ResourceManager.GetString("ManageFavoriteTideStationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metres.
        /// </summary>
        public static string Metres {
            get {
                return ResourceManager.GetString("Metres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minus_24 {
            get {
                object obj = ResourceManager.GetObject("minus_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minus_36 {
            get {
                object obj = ResourceManager.GetObject("minus_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] minus_48 {
            get {
                object obj = ResourceManager.GetObject("minus_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string MinutesCaptions {
            get {
                return ResourceManager.GetString("MinutesCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide Planning.
        /// </summary>
        public static string MobileApplicationTitle {
            get {
                return ResourceManager.GetString("MobileApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string NavigationButtonCaptionBack {
            get {
                return ResourceManager.GetString("NavigationButtonCaptionBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Low Water Height:.
        /// </summary>
        public static string NextLowWaterHeightCaption {
            get {
                return ResourceManager.GetString("NextLowWaterHeightCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Low Water Time:.
        /// </summary>
        public static string NextLowWaterTimeCaption {
            get {
                return ResourceManager.GetString("NextLowWaterTimeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from List.
        /// </summary>
        public static string PickFromListCaption {
            get {
                return ResourceManager.GetString("PickFromListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick From Map.
        /// </summary>
        public static string PickFromMapCaption {
            get {
                return ResourceManager.GetString("PickFromMapCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] plus_24 {
            get {
                object obj = ResourceManager.GetObject("plus_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] plus_36 {
            get {
                object obj = ResourceManager.GetObject("plus_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] plus_48 {
            get {
                object obj = ResourceManager.GetObject("plus_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl-R to Refresh Tide Heights.
        /// </summary>
        public static string RefreshTimeHeightTooltip {
            get {
                return ResourceManager.GetString("RefreshTimeHeightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Anchor Depth:.
        /// </summary>
        public static string SafeAnchorDepthCaption {
            get {
                return ResourceManager.GetString("SafeAnchorDepthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Anchoring Depth.
        /// </summary>
        public static string SafeAnchoringDepthHeaderCaption {
            get {
                return ResourceManager.GetString("SafeAnchoringDepthHeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save CSV File.
        /// </summary>
        public static string SaveFileCaption {
            get {
                return ResourceManager.GetString("SaveFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv files (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        public static string SaveFileFilter {
            get {
                return ResourceManager.GetString("SaveFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Selected Tide Height.
        /// </summary>
        public static string SelectedTideHeightCaption {
            get {
                return ResourceManager.GetString("SelectedTideHeightCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Tide Station.
        /// </summary>
        public static string SelectedTideStationCaption {
            get {
                return ResourceManager.GetString("SelectedTideStationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tide Station 1:.
        /// </summary>
        public static string SelectTideStationLeft {
            get {
                return ResourceManager.GetString("SelectTideStationLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tide Station 2:.
        /// </summary>
        public static string SelectTideStationRight {
            get {
                return ResourceManager.GetString("SelectTideStationRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on Tide Curve:.
        /// </summary>
        public static string ShowOnTideCurveCaption {
            get {
                return ResourceManager.GetString("ShowOnTideCurveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tide Curve.
        /// </summary>
        public static string ShowTideCurveCaption {
            get {
                return ResourceManager.GetString("ShowTideCurveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Date Time in UTC:.
        /// </summary>
        public static string ShowTimeInUtcCaption {
            get {
                return ResourceManager.GetString("ShowTimeInUtcCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sine_wave_24 {
            get {
                object obj = ResourceManager.GetObject("sine_wave_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sine_wave_36 {
            get {
                object obj = ResourceManager.GetObject("sine_wave_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sine_wave_48 {
            get {
                object obj = ResourceManager.GetObject("sine_wave_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Loading Tide Stations.
        /// </summary>
        public static string SnackbarMessageLoadingComplete {
            get {
                return ResourceManager.GetString("SnackbarMessageLoadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Tide Stations.
        /// </summary>
        public static string SnackbarMessageLoadingTideStations {
            get {
                return ResourceManager.GetString("SnackbarMessageLoadingTideStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract Charted Depth:.
        /// </summary>
        public static string SubtractChartedDepthCaption {
            get {
                return ResourceManager.GetString("SubtractChartedDepthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Tide Height.
        /// </summary>
        public static string TideHeight {
            get {
                return ResourceManager.GetString("TideHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval between Tide Heights:.
        /// </summary>
        public static string TideHeightsIntervalCaption {
            get {
                return ResourceManager.GetString("TideHeightsIntervalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of minutes required as an interval between the tidal heights. Valid range is 1 – 120 inclusive.
        /// </summary>
        public static string TideHeightsIntervalTooltip {
            get {
                return ResourceManager.GetString("TideHeightsIntervalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide Heights.
        /// </summary>
        public static string TideHeightsTitle {
            get {
                return ResourceManager.GetString("TideHeightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide Stations.
        /// </summary>
        public static string TideStationsCaption {
            get {
                return ResourceManager.GetString("TideStationsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tides.
        /// </summary>
        public static string TidesTitle {
            get {
                return ResourceManager.GetString("TidesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide Time.
        /// </summary>
        public static string TideTimeAxisTitle {
            get {
                return ResourceManager.GetString("TideTimeAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Tide Time.
        /// </summary>
        public static string TideTimeCaption {
            get {
                return ResourceManager.GetString("TideTimeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string TimeCaption {
            get {
                return ResourceManager.GetString("TimeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string ToCaption {
            get {
                return ResourceManager.GetString("ToCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todays Tides.
        /// </summary>
        public static string TodaysTidesCaption {
            get {
                return ResourceManager.GetString("TodaysTidesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find my location.
        /// </summary>
        public static string TooltipFindMyLocation {
            get {
                return ResourceManager.GetString("TooltipFindMyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels draught including safety factor.
        /// </summary>
        public static string TooltipVesselDraught {
            get {
                return ResourceManager.GetString("TooltipVesselDraught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels safety factor.
        /// </summary>
        public static string TooltipVesselSafetyFactor {
            get {
                return ResourceManager.GetString("TooltipVesselSafetyFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Draught Needed:.
        /// </summary>
        public static string TotalDraughtNeededCaption {
            get {
                return ResourceManager.GetString("TotalDraughtNeededCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC.
        /// </summary>
        public static string UtcCaption {
            get {
                return ResourceManager.GetString("UtcCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Details.
        /// </summary>
        public static string VesselDetailsCaption {
            get {
                return ResourceManager.GetString("VesselDetailsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Draught:.
        /// </summary>
        public static string VesselDraughtCaption {
            get {
                return ResourceManager.GetString("VesselDraughtCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Safety Factor:.
        /// </summary>
        public static string VesselSafetyFactorCaption {
            get {
                return ResourceManager.GetString("VesselSafetyFactorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Tide Stations on Map.
        /// </summary>
        public static string ViewTideStationsMapCaption {
            get {
                return ResourceManager.GetString("ViewTideStationsMapCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] waves_24 {
            get {
                object obj = ResourceManager.GetObject("waves_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] waves_36 {
            get {
                object obj = ResourceManager.GetObject("waves_36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] waves_48 {
            get {
                object obj = ResourceManager.GetObject("waves_48", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
